### ISSUE TITLE
kaitai-struct-runtime is not available as snapshot in oss-sonatype

### ISSUE THREAD

**Issue by ams-tschoening** [kaitai-io/kaitai_struct_gui#1]
With the default `pom.xml` I get the following error:

> [ERROR] Failed to execute goal on project kaitai_struct_visualizer_java: Could not resolve dependencies for project groupId:kaitai_struct_visualizer_java:jar:0.5-SNAPSHOT: Could not find artifact io.kaitai:kaitai-struct-runtime:jar:0.5-SNAPSHOT in oss-sonatype (https://oss.sonatype.org/content/repositories/snapshots/) -> [Help 1]

Looking at the URL, the directory for the runtime in deed doesn't contain any Jar currently:

https://oss.sonatype.org/content/repositories/snapshots/io/kaitai/kaitai-struct-runtime/

![no jar for kaitai-struct-runtime](https://cloud.githubusercontent.com/assets/6223655/20440379/25178d94-adc0-11e6-96f6-7b0e5c077f4d.png)

I changed the version from 

`<version>0.5-SNAPSHOT</version>`

to 

`<version>0.5</version>`

so the dependency was fetched from default Maven repos and that worked. Looks like the upload of the Jar is only missing by accident or such?

**Comment by GreyCat** [comment]
It's true that the project wasn't updated after 0.5 release. But it's kind of strange, as snapshot artifacts are routinely published. I've just published 0.6-SNAPSHOT and [it's there, on oss.sonatype.org](https://oss.sonatype.org/content/repositories/snapshots/io/kaitai/kaitai-struct-runtime/0.6-SNAPSHOT/). May be sonatype purges snapshots after some time?

**Comment by tschoening** [comment]
Guten Tag Mikhail Yakshin,
am Freitag, 18. November 2016 um 19:54 schrieben Sie:

> May be sonatype purges snapshots after some time?

At least the compiler is/was there:

https://oss.sonatype.org/content/repositories/snapshots/io/kaitai/kaitai-struct-compiler_2.11/

Mit freundlichen Grüßen,

Thorsten Schöning

-- 
Thorsten Schöning       E-Mail: Thorsten.Schoening@AM-SoFT.de
AM-SoFT IT-Systeme      http://www.AM-SoFT.de/

Telefon...........05151-  9468- 55
Fax...............05151-  9468- 88
Mobil..............0178-8 9468- 04

AM-SoFT GmbH IT-Systeme, Brandenburger Str. 7c, 31789 Hameln
AG Hannover HRB 207 694 - Geschäftsführer: Andreas Muchow

**Comment by GreyCat** [comment]
Indeed, Sonatype does snapshot purging: http://blog.sonatype.com/2009/09/nexus-scheduled-tasks/

Generally, snapshots are supposed to updated automatically from CI or something like that. Probably we should do so too...

**Comment by GreyCat** [comment]
Thanks to efforts of @Mingun, project is now resurrected and depends on release versions of runtime + compiler, both available at Maven Central for infinite time.

I believe this resolves this issue.
