### ISSUE TITLE
HexLib is a missing dependency in mvn

### ISSUE THREAD

**Issue by ams-tschoening** [kaitai-io/kaitai_struct_gui#2]
With the default `pom.xml` I get the following error:

> [ERROR] /C:/Users/tschoening/Downloads/kaitai_struct_gui-master/src/main/java/io/kaitai/struct/visualizer/VisualizerPanel.java:[3,25] package at.HexLib.library does not exist

For test purposes, I added the local lib provided in the repo as a dependency and that worked:

		<dependency>
			<groupId>at.HexLib</groupId>
			<artifactId>HexLib</artifactId>
			<version>0.0.0</version>
			<scope>system</scope>
			<systemPath>${project.basedir}/lib/HexLib.jar</systemPath>
		</dependency>

Is this dependency simply missing or did you have something different in mind how this should work in Maven?

**Comment by GreyCat** [comment]
I work with IDEA while building this project, so probably IDEA does some magic, appending `lib/*` stuff automatically into the classpath. Unfortunately, HexLib doesn't seem to be available as a proper published Maven artifact. Probably I should bug its author to publish it - but until then, I take it for granted that I can apply your patch as a solution for a clean maven build?

**Comment by tschoening** [comment]
Guten Tag Mikhail Yakshin,
am Freitag, 18. November 2016 um 19:56 schrieben Sie:

> Probably I should bug its author to
> publish it - but until then, I take it for granted that I can apply
> your patch as a solution for a clean maven build?

Maven is presenting a warning, but besides that it works:

> [INFO] Scanning for projects...
> [WARNING]
> [WARNING] Some problems were encountered while building the effective model for groupId:kaitai_struct_visualizer_java:jar:0.5-SNAPSHOT
> [WARNING] 'dependencies.dependency.systemPath' for at.HexLib:HexLib:jar should not point at files within the project directory, ${project.basedir}/lib/HexLib.jar will be unresolvable by dependent projects @ line 29, column 16
> [WARNING]
> [WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
> [WARNING]
> [WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
> [WARNING]

Mit freundlichen Grüßen,

Thorsten Schöning

-- 
Thorsten Schöning       E-Mail: Thorsten.Schoening@AM-SoFT.de
AM-SoFT IT-Systeme      http://www.AM-SoFT.de/

Telefon...........05151-  9468- 55
Fax...............05151-  9468- 88
Mobil..............0178-8 9468- 04

AM-SoFT GmbH IT-Systeme, Brandenburger Str. 7c, 31789 Hameln
AG Hannover HRB 207 694 - Geschäftsführer: Andreas Muchow
