### ISSUE TITLE
How to deal with missing dependencies during runtime?

### ISSUE THREAD

**Issue by ams-tschoening** [kaitai-io/kaitai_struct_gui#3]
After the changes from #1 and #2 I was able to build the project, but couldn't run it, because a lot of needed libs where in the local repo folder of Maven, which is by default not in the classpath. So I changed the `pom.xml` again and let Maven copy all dependencies to the build dir:

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-dependency-plugin</artifactId>
				<version>2.10</version>
				<executions>
					<execution>
						<id>copy-dependencies</id>
						<phase>package</phase>
						<goals>
							<goal>copy-dependencies</goal>
						</goals>
						<configuration>
							<outputDirectory>${project.build.directory}/lib</outputDirectory>
							<overWriteReleases>false</overWriteReleases>
							<overWriteSnapshots>false</overWriteSnapshots>
							<overWriteIfNewer>true</overWriteIfNewer>
						</configuration>
					</execution>
				</executions>
			</plugin>

With an additional shell script configuring the classpath as needed, I was able to start the GUI in the end:

	@ECHO OFF
	setlocal enabledelayedexpansion

	pushd target

	for /R "lib" %%i in (*.jar) do (
		SET CLASSPATH=!CLASSPATH!;%%i
	)
	SET CLASSPATH=!CLASSPATH!;kaitai_struct_visualizer_java-0.5-SNAPSHOT.jar

	:: A JDK is needed because of tools.jar, global "java" might provide a JRE instead, depending on
	:: settings of the Java control panel.
	"%JAVA_HOME%\bin\javaw.exe" io.kaitai.struct.visualizer.MainWindow "%USERPROFILE%\Desktop\Clipboard01.bmp" "%USERPROFILE%\Downloads\bmp.ksy"

	popd

I suggest you think of some way to provide the needed dependencies somehow, because I started without the Maven changes first by simply running the GUI and see how it's going until ClassNotFoundExceptions are thrown. It's pretty hard to get all the dependencies this way one by one. At the end I was even missing one so that my data file wasn't parsed at all, even though I didn't get any exception anymore.

Besides the above "solution", I tried building a fat jar, but using the following examples:

			<plugin>
				<artifactId>maven-assembly-plugin</artifactId>
				<configuration>
					<archive>
						<manifest>
							<mainClass>io.kaitai.struct.visualizer.MainWindow</mainClass>
						</manifest>
					</archive>
					<descriptorRefs>
						<descriptorRef>jar-with-dependencies</descriptorRef>
					</descriptorRefs>
				</configuration>
			</plugin>

http://stackoverflow.com/a/574650/2055163
http://stackoverflow.com/questions/1814526/problem-building-executable-jar-with-maven

But this failed in Maven already and I didn't care much anymore. But this might be a good solution, especially because one can simply call "java -jar ..." and doesn't need to know your main class name. Which I don't see documented anyway.

> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.2-beta-5:single (default-cli) on project kaitai_struct_visualizer_java: Execution default-cli of goal org.apache.maven.plugins:maven-assembly-plugin:2.2-beta-5:single failed: Plugin org.apache.maven.plugins:maven-assembly-plugin:2.2-beta-5 or one of its dependencies could not be resolved: Failed to collect dependencies at org.apache.maven.plugins:maven-assembly-plugin:jar:2.2-beta-5 -> org.apache.maven.shared:maven-common-artifact-filters:jar:1.1: Failed to read artifact descriptor for org.apache.maven.shared:maven-common-artifact-filters:jar:1.1: Could not transfer artifact org.apache.maven.shared:maven-common-artifact-filters:pom:1.1 from/to central (https://repo.maven.apache.org/maven2): hostname in certificate didn't match: <repo.maven.apache.org> != <repo1.maven.org> OR <repo1.maven.org> -> [Help 1]

**Comment by GreyCat** [comment]
Again, @Mingun seems to have resolved this problem with recent updates. Should now build and run cleanly.
